name: Publish Docker image

# Source 1: https://oalahurikar.github.io/app-dev-blog/Github/Github-Container-Registry
# Source 2: https://stackoverflow.com/a/3545363/8259309
# Source 3: https://stac\koverflow.com/a/2264537/8259309

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: mvn test

      - name: get-pom-version
        id: pom-version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build Docker image
#        Test the build locally with the following docker command.
#        docker build -t ghcr.io/matejveselucll/demo-cloud-and-operations-back-end-dev:v0.1.7 .
        run: docker build -t ghcr.io/$(echo "${{ github.repository_owner }}" | awk '{print tolower($0)}')/demo-cloud-and-operations-back-end-main:${{ steps.pom-version.outputs.version }} .

      - name: Push Docker image
        run: docker push ghcr.io/$(echo "${{ github.repository_owner }}" | awk '{print tolower($0)}')/demo-cloud-and-operations-back-end-main:${{ steps.pom-version.outputs.version }}